name: My Action

on:
  pull_request:
    types: [opened, reopened, edited]


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print issue number
        run: echo ${{ github.event.issue.number }}