name: Sync Review Status

on:
  # Requires the event trigger to be of type pull_request or pull_request_target
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  sync-review-status:
    runs-on: ubuntu-latest
    name: Get Linked Issues
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@v1.0
        id: linked-issues
        with:
          # Required: personal access token with permissions to archive cards. This needs to be set in Settings -> Secrets with a token that has permissions for all repos the issues are linked in for cross-repo functionality
          access-token: "${{ secrets.secret_key }}"

      - name: Move Issues to Ready for Review Column
        uses: kin/gh-action-move-issue-to-column@1.0
        with:
          access-token: "${{ secrets.secret_key }}"
          target-column: "Ready for Review"
          issues: ${{ steps.linked-issues.outputs.issues }}
