name: first workflow

on:
  push:
    branches: [ main ]


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print issue number
        run: echo "Issue number is ${{ github.event.issue.number }}"