name: My Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print issue number
        run: echo "Issue number ${{ toJSON(github.event) }}"