name: Has linked issues
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  check-linked-issues:
    name: Check if pull request has linked issues
    runs-on: ubuntu-latest
    steps:
      - name: Get issues
        id: get-issues
        uses: mondeja/pr-linked-issues-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print has linked issues
        id: has-linked-issues
        if: join(steps.get-issues.outputs.issues) != ''
        run: echo "Has linked issues"
      - name: Print has not linked issues
        if: steps.has-linked-issues.conclusion == 'skipped'
        run: echo "Has not linked issues"