name: I report linked issues that are not really linked
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  check-linked-issues-by-content:
    name: Has "linked issues" defined by PR content
    runs-on: ubuntu-latest
    steps:
      - name: Get issues
        id: get-issues
        uses: mondeja/pr-linked-issues-action@v2
        with:
          add_links_by_content: |
            **Closes**: #{issue_number}
            #
            # You can add comments that will be ignored
            #
            :wrench: the problem #{issue_number} like a boss
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print linked issue numbers
        run: echo ${{ steps.get-issues.outputs.issues }}